### ISSUE TITLE
Unable to compile on Ubuntu 14.04 due to 'struct wl_list' has no member named 'link'

### ISSUE THREAD

**Issue by markcallen** [raspberrypi/maynard#29]
Followed the instructions from the wiki Develop-on-a-computer

Get the following errors when running make install in the maynard directory:

make[2]: Entering directory `/home/vagrant/maynard/maynard/shell'
  CC       shell-helper.lo
shell-helper.c: In function 'configure_surface':
shell-helper.c:73:41: error: 'struct wl_list' has no member named 'link'
  if (wl_list_empty(&new_view->layer_link.link)) {
                                         ^
shell-helper.c: In function 'configure_panel':
shell-helper.c:122:37: error: 'struct wl_list' has no member named 'link'
  if (wl_list_empty(&view->layer_link.link)) {
                                     ^
In file included from shell-helper.c:25:0:
shell-helper.c: In function 'shell_helper_set_panel':
shell-helper.c:148:18: error: 'struct wl_list' has no member named 'link'
         view_list.link);
                  ^
/home/vagrant/maynard/_inst/include/weston/compositor.h:49:33: note: in definition of macro 'container_of'
  const __typeof__( ((type *)0)->member ) *__mptr = (ptr); \
                                 ^
shell-helper.c:146:53: error: 'struct wl_list' has no member named 'link'
  helper->panel_layer = container_of(view->layer_link.link.next,
                                                     ^
/home/vagrant/maynard/_inst/include/weston/compositor.h:49:53: note: in definition of macro 'container_of'
  const __typeof__( ((type *)0)->member ) *__mptr = (ptr); \
                                                     ^
In file included from /usr/include/alloca.h:24:0,
                 from /usr/include/stdlib.h:492,
                 from /home/vagrant/maynard/_inst/include/weston/zalloc.h:30,
                 from /home/vagrant/maynard/_inst/include/weston/compositor.h:40,
                 from shell-helper.c:25:
/home/vagrant/maynard/_inst/include/weston/compositor.h:50:29: error: 'struct wl_list' has no member named 'link'
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
shell-helper.c:146:24: note: in expansion of macro 'container_of'
  helper->panel_layer = container_of(view->layer_link.link.next,
                        ^
make[2]: *** [shell-helper.lo] Error 1
make[2]: Leaving directory`/home/vagrant/maynard/maynard/shell'
make[1]: **\* [install] Error 2
make[1]: Leaving directory `/home/vagrant/maynard/maynard/shell'
make: **\* [install-recursive] Error 1
